FORMAT: 1A
HOST: https://regent-api.alpha.org/2

# CRM (v2)

This API provides access to functions of Regent CRM.

## Authentication

You will need to use a user's access token when making requests to any non-public endpoint.

Make sure they have the _ACS_ permission if they are making changes to other individuals apart from themselves.

# Group Me

## Me [/me]

Manage an individual's attributes. 
+ Attributes (Individual)


### Me [GET]

+ Request

    + Headers

            Authorization: Bearer {access_token}


+ Response 200 (application/json)

    + Body

            {"individual":{"id": 1, "primaryEmail":"jordan@cultivate4.com","primaryAddress":{"addressLine1":null,"addressLine2":null,"name":null,"county":"Greater London","postcode":null,"countryCode":"GB","latitude":null,"longitude":null},"unsubscribed":true,"firstName":"Jordan","lastName":"de Laune","gender":"M","dateOfBirth":"1987-08-25T00:00:00+0000","locale":null,"sourceSystem":"1"}}


### Update me [PUT]

+ Request

    + Headers

            Authorization: Bearer {access_token}

    + Body

            {"firstName":"Jordan","lastName":"de Laune","gender":"M","dateOfBirth":"1987-08-25T00:00:00+0000","address":{"county":"Greater London","country":"GB"},"email":"jordan@cultivate4.com","unsubscribed":true}


+ Response 200 (application/json)


    + Body

            {"individual":{"id": 1, "primaryEmail":"jordan@cultivate4.com","primaryAddress":{"addressLine1":null,"addressLine2":null,"name":null,"county":"Greater London","postcode":null,"countryCode":"GB","latitude":null,"longitude":null},"unsubscribed":true,"firstName":"Jordan","lastName":"de Laune","gender":"M","dateOfBirth":"1987-08-25T00:00:00+0000","locale":null,"sourceSystem":"1"}}

# Group Attributes

## Attributes [/individuals/{individualId}/attributes]

Manage an individual's attributes

### List all an individual's attributes [GET]

+ Parameters
    + individualId (required, integer, `1`) ... Id of an individual

+ Request

    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)

    + Body

            {"attributes":[{"id":4,"lookupFullDesc":"Do not E-mail","lookupTypeDesc":"Privacy","detail":null,"sourceSystem":"Regent"}]}


### Add an attribute [POST]

+ Parameters
    + individualId (required, integer, `1`) ... Id of an individual

+ Request

    + Headers

            Authorization: Bearer {access_token}

    + Body

            {"lookupTypeDesc":"Privacy","lookupFullDesc":"Do not E-mail","detail":"Do not email this individual"}

+ Response 201 (application/json)


    + Body

            {"attribute":{"id":5,"lookupFullDesc":"Do not E-mail","lookupTypeDesc":"Privacy","detail":"Do not email this individual","sourceSystem":"Regent"}}

## An attribute [/individuals/{individualId}/attributes/{attributeId}]

Actions to take against an individuals attribute

### Remove an attribute [DELETE]

+ Parameters
    + individualId (required, integer, `1`) ... Id of an individual
    + attributeId (required, integer, `1`) ... Id of an attribute

+ Request

    + Headers

            Authorization: Bearer {access_token}

+ Response 204 (application/json)

# Group Common Data
Common data structures used in requests and responses are defined here. This section
will be migrated to **Data Structures** when a bug relating to definition of types is fixed.
## IndividualLocation [/fake1]
+ Attributes
    + id: 1234 (number) - location ID
    + type (enum) - address type
        + `Previous`
        + `Primary`
        + `Secondary`
        + `Business`
        + `Mail Returned / Incorrect`
        + `Statement`
        + `Org`
    + validFrom - valid from date
    + validTo - valid to date
    + mainLocation (enum) - is this the main location?
        + Y
        + N
    + sourceSystem: Regent - source of this record
    + venue (Venue) - the address of this location
    + household (number)

## Individual [/fake2]
+ Attributes
    + id: 123 (number) - individual ID
    + username: alphasample - OAuth user name
    + householdName - household name
    + householdPosition (enum) - household position
        + Head
        + Spouse
        + Child
        + Other
    + prefix - their prefix
    + title: Ms - title
    + firstName: Jane - first name
    + middleName: Susan - middle name
    + lastName: Doe - surname
    + initials - initials
    + knownAs - name they are known by
    + suffix - suffix
    + gender (enum) - gender
        + M
        + F
    + dateOfBirth: `1987-08-25T00:00:00+0000` - date of birth
    + type (enum) - contact type
        + `Child`
        + `Child/Yth`
        + `Divorced`
        + `Married`
        + `Other`
        + `Separated`
        + `Single`
        + `Unknown`
        + `Widowed`
    + individualStatus (enum) - status
        + `Active`
        + `Active - HTB Member`
        + `Attendee`
        + `Child of Member`
        + `Contributor Only`
        + `Deceased`
        + `Event Attendee`
        + `Event Prospect`
        + `Home Focus Attendee`
        + `Inactive`
        + `Member`
        + `Merge Candiate`
        + `Moved away`
        + `New Checkin`
        + `New From Small Group`
        + `New from Website`
        + `Organisation`
        + `Past Giver`
        + `Retired`
        + `RTS-Inactive`
        + `The Trust Member`
        + `Visiting Church`
    + statusDate: `2016-01-01T00:00:00+0000` - when status was set
    + honours - any honours
    + salutation - salutation
    + labelName - label name
    + locale: en - locale
    + firstRecord: `2016-01-01T00:00:00+0000` - first record date
    + sourceSystem: Regent - source of the record
    + comments - any comments
    + recordInRe: `2016-01-01T00:00:00+0000`
    + communications (array) - means of communication
        + type (enum)
            + `Alternate Email`
            + `Alternate Phone`
            + `Email`
            + `Facebook`
            + `Fax`
            + `Home Email`
            + `Home Phone`
            + `Infellowship Login`
            + `Mobile Phone`
            + `Other Email`
            + `Other Phone`
            + `Skype Username`
            + `Twitter`
            + `Web Address`
            + `Work Email`
            + `Work Phone`
        + value: `example@example.com`
    + emails (array) - email addresses from communications
        + `example@example.com`
    + locations (array[IndividualLocation]) - locations for this contact
    + addresses (array[Venue]) - addresses of locations
    + roles
    + attributes
    + household
    + family

## Venue [/fake3]
+ Attributes
    + id: 123 (number) - individual ID
    + name: `Example Buildings` - location name
    + address1: `22 Instance Place" - 1st line of address
    + address2 - 2nd line of address
    + address3 - 3rd line of address
    + town: Sampleton - town/city
    + county: Sampleshire - county/state
    + postcode: `SS99 1SS` - postcode/zip
    + country: `United Kingdom` - country
    + countryCode: GB - country code
    + addressComment - comment
    + sourceSystem: Regent - source of this record
    + inCourses: true (boolean) 
    + latitude: `51.5072` (number) - latitude of venue
    + longitude: `-0.1275` (number) - longitude of venue
    + distance: 20 (number) - distance in kilometers when subject of a query with respect to coordinates
